WeightQ:
  Kpcom:
    x: 50
    y: 50
    z: 100
  Kdcom:
    x: 1
    y: 1
    z: 5
  Kpbase:
    roll: 20
    pitch: 10
    yaw: 10
  Kdbase:
    roll: 1
    pitch: 1
    yaw: 1
WeightR:
  x: 0.000001
  y: 0.000001
  z: 0.000001
WeightS:
  x: 0.0001
  y: 0.0001
  z: 0.0001
alpha: 1
mass: 9
inertia:
  ixx: 0.07
  iyy: 0.26
  izz: 0.242
  ixy: 0
  ixz: 0
  iyz: 0
mu: 0.4
dt: 0.002
horizon: 20
duration_between_mpc: 10
iterations_between_segment: 20